name: CI/CD with Jib and Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Cachear dependencias de Maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 4️⃣ Construir la imagen con Jib
      - name: Build Docker image with Jib
        run: |
          mvn compile jib:dockerBuild -Dimage=shoestore:latest
          echo "✅ Imagen construida con Jib"
          docker images | grep shoestore

      # 5️⃣ Instalar docker-compose en el runner
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 6️⃣ Levantar los contenedores usando docker-compose
      - name: Run containers with docker-compose
        run: |
          docker-compose up -d --build
          echo "✅ Contenedores levantados"
          docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"


