name: CI/CD with Jib and Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and push image with Jib
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          mvn compile jib:build \
            -Dimage=${DOCKER_USERNAME}/shoestore:latest \
            -Djib.to.auth.username=${DOCKER_USERNAME} \
            -Djib.to.auth.password=${DOCKER_PASSWORD}

      - name: Notify Hookdeck (trigger deploy on PC)
        run: |
          curl -X POST https://hkdk.events/dx04bea4pkpd6h \
          -H "Content-Type: application/json" \
          -d '{"event":"deploy","image":"shoestore:latest"}'

  


